### ISSUE TITLE
Can't find files

### ISSUE THREAD

**Issue by hippyjim** [kahwee/yii-opauth#6]
"include(OpauthStrategy.php): failed to open stream: No such file or directory"

I've no idea if I've set this up properly. Is there more config than what is in the doc, because it doesn't seem to work.

I'm attempting to use this to sign my users in with Google. This is a default generated Yii app. Any clues?

**Comment by uzyn** [comment]
@hippyjim This repository is dead. You might want to look into implementing it yourself.

**Comment by hippyjim** [comment]
Wow, ok, thanks.

This is like the 4th plugin I've tried now, and they all seem to be half completed. I guess I better roll my own. Thanks.
